import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='EmailBudget', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('period', models.CharField(max_length=10, unique=True)), ('reserved', models.PositiveIntegerField(default=0)), ('submitted', models.PositiveIntegerField(default=0)), ('updated_at', models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name='EmailSuppression', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('recipient_hmac', models.CharField(max_length=64, unique=True)), ('reason', models.CharField(max_length=32)), ('active', models.BooleanField(default=True)), ('created_at', models.DateTimeField(default=django.utils.timezone.now)), ('released_at', models.DateTimeField(blank=True, null=True))]),
        migrations.CreateModel(name='EmailTemplateArtifact', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('kind', models.CharField(max_length=64)), ('version', models.PositiveIntegerField()), ('subject', models.CharField(max_length=200)), ('text_body', models.TextField()), ('html_body', models.TextField()), ('content_hash', models.CharField(max_length=64)), ('created_at', models.DateTimeField(default=django.utils.timezone.now))], options={'constraints': [models.UniqueConstraint(fields=('kind', 'version'), name='notifications_template_kind_version')]}),
        migrations.CreateModel(name='ProviderEvent', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('provider', models.CharField(max_length=32)), ('event_id', models.CharField(max_length=128)), ('event_type', models.CharField(max_length=64)), ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=128)), ('normalized_data', models.JSONField(default=dict)), ('occurred_at', models.DateTimeField(null=True)), ('received_at', models.DateTimeField(default=django.utils.timezone.now)), ('processed_at', models.DateTimeField(null=True))], options={'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='notifications_provider_event_unique')]}),
        migrations.CreateModel(name='EmailOutbox', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('business_key', models.CharField(max_length=200, unique=True)), ('intent', models.CharField(max_length=64)), ('encrypted_recipient', models.TextField()), ('recipient_hmac', models.CharField(db_index=True, max_length=64)), ('encrypted_context', models.TextField()), ('crypto_key_id', models.CharField(max_length=32)), ('idempotency_key', models.CharField(max_length=200, unique=True)), ('payload_hash', models.CharField(max_length=64)), ('status', models.CharField(choices=[('pending', 'Pendente'), ('leased', 'Reservado'), ('accepted', 'Aceito'), ('delivered', 'Entregue'), ('failed', 'Falhou'), ('expired', 'Expirou'), ('suppressed', 'Suprimido'), ('unknown', 'Desconhecido')], db_index=True, default='pending', max_length=16)), ('attempts', models.PositiveSmallIntegerField(default=0)), ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)), ('send_before', models.DateTimeField()), ('lease_token', models.UUIDField(blank=True, null=True)), ('lease_expires_at', models.DateTimeField(blank=True, null=True)), ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=128)), ('submitted_at', models.DateTimeField(blank=True, null=True)), ('delivered_at', models.DateTimeField(blank=True, null=True)), ('last_error_code', models.CharField(blank=True, max_length=64)), ('created_at', models.DateTimeField(default=django.utils.timezone.now)), ('updated_at', models.DateTimeField(auto_now=True)), ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notifications.emailtemplateartifact'))]),
    ]
