# Generated by Django 5.0.14 on 2026-08-22 20:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('aplica_dizimo', models.BooleanField(default=False, help_text='Marca o canal usado como base do dízimo (ex.: Canal B).')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canais',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('tipo', models.CharField(choices=[('CONTA_CORRENTE', 'Conta corrente'), ('DINHEIRO', 'Dinheiro'), ('CARTAO_CREDITO', 'Cartão de crédito'), ('CARTAO_TERCEIRO', 'Cartão de terceiro')], default='CONTA_CORRENTE', max_length=20)),
                ('titular_nome', models.CharField(blank=True, help_text='Ex.: "Terceiro", quando o titular não é sócio.', max_length=60)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('categoria', models.CharField(choices=[('BOLO_POTE', 'Bolo de pote'), ('MOUSSE', 'Mousse'), ('PUDIM', 'Pudim'), ('TORTA', 'Torta'), ('BROWNIE', 'Brownie'), ('OVO_PASCOA', 'Ovo de Páscoa'), ('ENERGETICO', 'Energético'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('unidade', models.CharField(choices=[('POTE', 'Pote'), ('UNIDADE', 'Unidade'), ('FATIA', 'Fatia'), ('KG', 'Kg')], default='POTE', max_length=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('custo_estimado_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimativa para precificação. NÃO é a fonte do custo contábil.', max_digits=10)),
                ('sazonal', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('contato', models.CharField(blank=True, help_text='Telefone/WhatsApp', max_length=40)),
                ('forma_pagamento_preferida', models.CharField(blank=True, choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão'), ('OUTRO', 'Outro')], max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('canal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='cadastros.canal')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField(help_text='1 a 12')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada')], default='ABERTA', max_length=10)),
                ('data_fechamento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('ano', 'mes')},
            },
        ),
    ]
