# Complemento do docker-compose.yml do sistema para o ambiente de teste do P2.
services:
  api:
    volumes:
      - ../ambiente:/p2:ro
    environment:
      - PYTHONPATH=/p2
      - DJANGO_SETTINGS_MODULE=configuracao
