"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import re

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_list(name, default=''):
    """Lê uma variável de ambiente separada por vírgula e devolve uma lista limpa."""
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(',') if item.strip()]


def secret_value(name, default=''):
    file_path = os.environ.get(f'{name}_FILE')
    if file_path:
        try:
            return Path(file_path).read_text(encoding='utf-8').strip()
        except OSError as exc:
            raise ImproperlyConfigured(f'Não foi possível ler {name}_FILE.') from exc
    return os.environ.get(name, default)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-default-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG') == '1'

if not DEBUG and SECRET_KEY == 'django-insecure-default-key':
    raise ImproperlyConfigured('Defina SECRET_KEY no ambiente de produção.')
if not DEBUG and re.fullmatch(r'[0-9a-f]{96}', SECRET_KEY) is None:
    raise ImproperlyConfigured(
        'SECRET_KEY de produção deve conter exatamente 48 bytes aleatórios '
        'codificados como 96 caracteres hexadecimais minúsculos.'
    )

JWT_SIGNING_KEY = os.environ.get('JWT_SIGNING_KEY')
if DEBUG:
    JWT_SIGNING_KEY = JWT_SIGNING_KEY or SECRET_KEY
elif (
    JWT_SIGNING_KEY is None
    or re.fullmatch(r'[0-9a-f]{96}', JWT_SIGNING_KEY) is None
    or JWT_SIGNING_KEY == SECRET_KEY
):
    raise ImproperlyConfigured(
        'JWT_SIGNING_KEY de produção deve ser uma chave separada de 48 bytes '
        'aleatórios codificados como 96 caracteres hexadecimais minúsculos.'
    )

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1')

# Recursos de desenvolvimento ficam fechados por padrão em produção.
ALLOW_PUBLIC_REGISTRATION = os.environ.get(
    'ALLOW_PUBLIC_REGISTRATION', '1' if DEBUG else '0'
) == '1'
ENABLE_API_DOCS = os.environ.get(
    'ENABLE_API_DOCS', '1' if DEBUG else '0'
) == '1'
ENABLE_INTERNAL_API = os.environ.get(
    'ENABLE_INTERNAL_API', '1' if DEBUG else '0'
) == '1'
WEB_SESSION_ENABLED = os.environ.get('WEB_SESSION_ENABLED', '1') == '1'
API_JWT_ENABLED = os.environ.get('API_JWT_ENABLED', '0') == '1'
PUBLIC_ADMIN_ENABLED = os.environ.get('PUBLIC_ADMIN_ENABLED', '0') == '1'
WEB_SESSION_IDLE_SECONDS = int(os.environ.get('WEB_SESSION_IDLE_SECONDS', '1800'))
WEB_SESSION_ABSOLUTE_SECONDS = int(os.environ.get('WEB_SESSION_ABSOLUTE_SECONDS', '43200'))
ACCOUNT_RATE_LIMIT_ENABLED = os.environ.get('ACCOUNT_RATE_LIMIT_ENABLED', '0' if DEBUG else '1') == '1'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_spectacular',
    'corsheaders',
    'rest_framework',
    'rest_framework_api_key',
    'rest_framework_simplejwt.token_blacklist',
    'accounts',
    'notifications',
    'cadastros',
    'operacao',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': os.environ.get('POSTGRES_HOST', 'db'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        'CONN_MAX_AGE': int(os.environ.get('POSTGRES_CONN_MAX_AGE', '60')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'accounts.password_validation.MaximumLengthValidator',
        'OPTIONS': {'max_length': 128},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 15},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = os.environ.get('LANGUAGE_CODE', 'pt-br')

TIME_ZONE = os.environ.get('TIME_ZONE', 'America/Sao_Paulo')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.CustomUser'

DRF_AUTHENTICATION_CLASSES = []
if WEB_SESSION_ENABLED:
    DRF_AUTHENTICATION_CLASSES.append('accounts.authentication.VersionedSessionAuthentication')
if API_JWT_ENABLED:
    DRF_AUTHENTICATION_CLASSES.append('rest_framework_simplejwt.authentication.JWTAuthentication')


# Configurações do Django Rest Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': DRF_AUTHENTICATION_CLASSES,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '5000/day',
        'anon': '120/hour',
        'login': '10/min',
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'API do Sistema Saborino',
    'DESCRIPTION': 'Documentação automática da API do Sistema Saborino, gerada com DRF e Docker.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,

    'SECURITY': [
        {'bearerAuth': []},
        {'ApiKeyAuth': []},
    ],
    
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'ApiKeyAuth': {
                'type': 'apiKey',
                'in': 'header',
                'name': 'X-Api-Key',
            }
        }
    }
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'SIGNING_KEY': JWT_SIGNING_KEY,
}

API_KEY_CUSTOM_HEADER = "HTTP_X_API_KEY"

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
ACCOUNT_RATE_LIMIT_REDIS_URL = os.environ.get('ACCOUNT_RATE_LIMIT_REDIS_URL', CELERY_BROKER_URL)
CELERY_TIMEZONE = "America/Sao_Paulo"
CELERY_BEAT_SCHEDULE = {
    'dispatch-email-outbox': {'task': 'notifications.dispatch_email_outbox', 'schedule': 5.0},
    'process-email-provider-events': {'task': 'notifications.process_provider_events', 'schedule': 5.0},
    'sweep-email-leases': {'task': 'notifications.sweep_email_leases', 'schedule': 60.0},
    'mark-unknown-email-deliveries': {'task': 'notifications.mark_unknown_email_deliveries', 'schedule': 3600.0},
    'apply-email-retention': {'task': 'notifications.apply_email_retention', 'schedule': 86400.0},
}
CELERY_TASK_ROUTES = {
    'notifications.*': {'queue': 'email_send'},
}

CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173',
)

CSRF_TRUSTED_ORIGINS = env_list(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173',
)

_default_email_backend = (
    'django.core.mail.backends.console.EmailBackend'
    if DEBUG
    else 'django.core.mail.backends.dummy.EmailBackend'
)
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', _default_email_backend)
if not DEBUG and EMAIL_BACKEND == 'django.core.mail.backends.console.EmailBackend':
    raise ImproperlyConfigured(
        'O backend de e-mail console não é permitido em produção: mensagens de '
        'autenticação podem conter links secretos.'
    )

# Configurações de SMTP (só serão usadas se o EMAIL_BACKEND for SMTP)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = os.getenv('EMAIL_PORT', 587)
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

DEFAULT_FROM_EMAIL = os.getenv(
    'DEFAULT_FROM_EMAIL',
    'Sistema Saborino <noreply@sistemasaborino.com.br>',
)

FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')
EMAIL_DISPATCH_ENABLED = os.environ.get('EMAIL_DISPATCH_ENABLED', '0') == '1'
EMAIL_SEND_CAPABLE = os.environ.get('EMAIL_SEND_CAPABLE', '0') == '1'
EMAIL_DATA_CAPABLE = os.environ.get('EMAIL_DATA_CAPABLE', '0') == '1'
EMAIL_WEBHOOK_CAPABLE = os.environ.get('EMAIL_WEBHOOK_CAPABLE', '0') == '1'
PASSWORD_RESET_ENABLED = os.environ.get('PASSWORD_RESET_ENABLED', '1' if DEBUG else '0') == '1'
EMAIL_VERIFICATION_ENABLED = os.environ.get('EMAIL_VERIFICATION_ENABLED', '1' if DEBUG else '0') == '1'
EMAIL_CHANGE_ENABLED = os.environ.get('EMAIL_CHANGE_ENABLED', '1' if DEBUG else '0') == '1'
EMAIL_PROVIDER = os.environ.get('EMAIL_PROVIDER', 'fake' if DEBUG else 'disabled')
EMAIL_CRYPTO_KEY_ID = os.environ.get('EMAIL_CRYPTO_KEY_ID', 'dev-v1')
EMAIL_CRYPTO_KEYS = [item.strip() for item in secret_value('EMAIL_CRYPTO_KEYS').replace('\n', ',').split(',') if item.strip()]
EMAIL_LOOKUP_HMAC_KEY = secret_value('EMAIL_LOOKUP_HMAC_KEY')
RESEND_API_KEY = secret_value('RESEND_API_KEY')
RESEND_WEBHOOK_SECRET = secret_value('RESEND_WEBHOOK_SECRET')
ACCOUNT_ACTION_SIGNING_KEY = secret_value('ACCOUNT_ACTION_SIGNING_KEY', SECRET_KEY if DEBUG else '')
ACCOUNT_ACTION_SIGNING_KEY_ID = os.environ.get('ACCOUNT_ACTION_SIGNING_KEY_ID', 'v1')
EMAIL_FROM = os.environ.get('EMAIL_FROM', 'Saborino <acesso@saborino.example.com>')
EMAIL_REPLY_TO = os.environ.get('EMAIL_REPLY_TO', 'suporte@saborino.example.com')
EMAIL_TEST_ALLOWLIST = env_list('EMAIL_TEST_ALLOWLIST')
EMAIL_DAILY_BUDGET = int(os.environ.get('EMAIL_DAILY_BUDGET', '80'))
EMAIL_MONTHLY_BUDGET = int(os.environ.get('EMAIL_MONTHLY_BUDGET', '2400'))
RECOVERY_COOKIE_NAME = '__Host-recovery' if not DEBUG else 'saborino_recovery_dev'

if not DEBUG and EMAIL_DATA_CAPABLE:
    if not EMAIL_CRYPTO_KEYS or not EMAIL_LOOKUP_HMAC_KEY:
        raise ImproperlyConfigured('Fluxos de e-mail exigem segredos dedicados de criptografia/HMAC.')
if not DEBUG and EMAIL_SEND_CAPABLE:
    if EMAIL_PROVIDER != 'resend' or not RESEND_API_KEY:
        raise ImproperlyConfigured('Worker de envio exige provedor Resend e chave send-only.')
if not DEBUG and EMAIL_WEBHOOK_CAPABLE:
    if not RESEND_WEBHOOK_SECRET:
        raise ImproperlyConfigured('Ingestão de webhook exige segredo Resend dedicado.')
    if not ACCOUNT_ACTION_SIGNING_KEY or ACCOUNT_ACTION_SIGNING_KEY == SECRET_KEY:
        raise ImproperlyConfigured('API de ações de conta exige chave de assinatura dedicada.')

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = '__Host-session' if not DEBUG else 'saborino_session_dev'
SESSION_COOKIE_PATH = '/'
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = WEB_SESSION_ABSOLUTE_SECONDS
SESSION_SAVE_EVERY_REQUEST = False
CSRF_COOKIE_NAME = '__Host-csrf' if not DEBUG else 'saborino_csrf_dev'
CSRF_COOKIE_PATH = '/'
CSRF_COOKIE_DOMAIN = None
CSRF_COOKIE_SAMESITE = 'Lax'


# === Segurança em produção ===
# Só entram em vigor com DEBUG=0. Em dev nada disso é aplicado, para não
# quebrar o acesso via http://localhost.
if not DEBUG:
    # O nginx termina o TLS e repassa o protocolo original neste header.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', '1') == '1'

    SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', '1') == '1'
    CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', '1') == '1'
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'

    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', 60 * 60 * 24 * 30))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', '0') == '1'
    SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', '0') == '1'

    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
