# Generated by Django 5.0.14 on 2026-08-22 20:40

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dizimo_percentual', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('dizimo_ativo', models.BooleanField(default=True)),
                ('prolabore_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('prolabore_valor_fixo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração financeira',
                'verbose_name_plural': 'Configuração financeira',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('descricao', models.CharField(help_text='Item comprado (texto livre no MVP).', max_length=120)),
                ('quantidade', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('situacao', models.CharField(choices=[('PAGA', 'Paga'), ('A_PAGAR', 'A pagar')], default='PAGA', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='cadastros.competencia')),
                ('conta_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='cadastros.conta')),
                ('produto_rateio', models.ForeignKey(blank=True, help_text='Produto ao qual o custo é atribuído. Vazio = Geral.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='cadastros.produto')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão'), ('OUTRO', 'Outro')], default='PIX', max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='cadastros.cliente')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='cadastros.competencia')),
                ('conta_recebimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='cadastros.conta')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Recebivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebiveis', to='cadastros.cliente')),
            ],
            options={
                'verbose_name': 'Recebível',
                'verbose_name_plural': 'Recebíveis',
                'ordering': ['venda__data_venda', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoAlocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='operacao.pagamento')),
                ('recebivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='operacao.recebivel')),
            ],
            options={
                'verbose_name': 'Alocação de pagamento',
                'verbose_name_plural': 'Alocações de pagamento',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField(default=django.utils.timezone.localdate)),
                ('socio_destino', models.CharField(choices=[('NOS', 'Nós'), ('S1', 'Sócio 1'), ('S2', 'Sócio 2')], default='NOS', max_length=5)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('canal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='cadastros.canal')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='cadastros.cliente')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='cadastros.competencia')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_venda', '-id'],
            },
        ),
        migrations.AddField(
            model_name='recebivel',
            name='venda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recebivel', to='operacao.venda'),
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Snapshot analítico. NÃO alimenta o resultado contábil (que usa custo de período).', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='cadastros.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='operacao.venda')),
            ],
            options={
                'verbose_name': 'Item de venda',
                'verbose_name_plural': 'Itens de venda',
            },
        ),
        migrations.CreateModel(
            name='ProducaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_produzida', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10)),
                ('meta_producao', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producoes', to='cadastros.competencia')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producoes', to='cadastros.produto')),
            ],
            options={
                'verbose_name': 'Produção do produto',
                'verbose_name_plural': 'Produção dos produtos',
                'ordering': ['produto__nome'],
                'unique_together': {('produto', 'competencia')},
            },
        ),
    ]
